# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'
pod 'Firebase/Analytics'



target 'io.planit.planit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!




  # Pods for io.planit.planit
  target 'io.planit.planitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'io.planit.planit-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for io.planit.planit-tvOS

  target 'io.planit.planit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

